name: Free space
description: Remove unwanted software to increase available space on GHA build VM.

on:
  push:

jobs:
  restore:
    runs-on: ubuntu-latest
    steps:
      - name: Restore from cache
        uses: ./.github/actions/cache-images
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        shell: bash
        run: docker pull dockereng/export-build
