name: Free space
description: Remove unwanted software to increase available space on GHA build VM.

on:
  push:

jobs:
  cache:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache common images
        uses: ./.github/actions/cache-common-images
  pull:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Cache common images
        uses: ./.github/actions/cache-common-images
      - name: Test
        shell: bash
        run: docker pull dockereng/export-build
